name: stream_channel
version: 1.1.0
description: An abstraction for two-way communication channels.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/stream_channel
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  async: '^1.8.0'
  stack_trace: '^1.0.0'
dev_dependencies:
  test: '^0.12.0'
